apiVersion: v1
kind: Pod
metadata:
  name: mssql-pod
  labels:
    app: microservices-webapi
    name: mssql-pod
spec:
  containers:
    - name: mssql
      image: mcr.microsoft.com/mssql/server
      ports:
        - containerPort: 1433
      env:
      - name: ACCEPT_EULA
        value: "Y"
      - name: SA_PASSWORD
        value: "$Ramirez42"